# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-
require './lib/evergreen/version'

Gem::Specification.new do |s|
  s.name = %q{evergreen}
  s.version = Evergreen::VERSION
  s.author = "Jean-Denis Vauguet <jd@vauguet.fr>"
  s.description = %q{Evergreen provides you with tree behaviors to mixin and tree classes to inherit from. Raw tree, common binary trees, custom trees...}
  s.email = %q{jd@vauguet.fr}
  s.files = Dir["lib/**/*"] + ["LICENSE", "Rakefile", "README.md"]
  s.homepage = %q{http://github.com/chikamichi/evergreen}
  s.summary = %q{A fully fledged tree library for Ruby.}
  s.add_dependency "activesupport"
  s.add_dependency "facets"
  s.add_development_dependency "rspec"
  s.add_development_dependency "yard"
end

