# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{evergreen}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jean-Denis Vauguet"]
  s.date = %q{2010-04-04}
  s.description = %q{Evergreen provides you with tree behaviors to mixin and tree classes to inherit from. Raw tree, common binary trees, custom trees...}
  s.email = %q{jd@vauguet.fr}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "evergreen.gemspec",
     "lib/evergreen.rb",
     "lib/evergreen/builders/raw_tree.rb",
     "lib/evergreen/builders/tree.rb",
     "lib/evergreen/classes/tree_classes.rb",
     "lib/evergreen/ext/ext.rb",
     "lib/evergreen/raw_tree_node.rb",
     "lib/evergreen/support/branch.rb",
     "lib/evergreen/support/support.rb",
     "lib/evergreen/tree_api.rb",
     "spec/raw_tree_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tree_spec.rb"
  ]
  s.homepage = %q{http://github.com/chikamichi/evergreen}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A fully fledged tree library for Ruby.}
  s.test_files = [
    "spec/raw_tree_spec.rb",
     "spec/spec_helper.rb",
     "spec/tree_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

